/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidad_grupo_63.vistas;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JLabel;

/**
 *
 * @author crist
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    
    public final int WIDTH = 970;
    public final int HEIGHT = 520;
    
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); // MENÚ APARECE EN EL MEDIO
        Home home = new Home(); // INSTANCIA DE JPANEL PARA SETEAR QUE HACE
        home.setSize(WIDTH, HEIGHT); //SE ABRE LA PÁGINA HOME
        home.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(home);
        contenido.revalidate();
        contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contenido = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        btnGestionMaterias = new javax.swing.JLabel();
        btnGestionAlumnos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInscripciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1218, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 170, 228));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(970, 520));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel1.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        btnHome.setBackground(new java.awt.Color(90, 184, 233));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setText("HOME");
        btnHome.setOpaque(true);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 50));

        btnGestionMaterias.setBackground(new java.awt.Color(90, 184, 233));
        btnGestionMaterias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionMaterias.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionMaterias.setText("GESTION MATERIAS");
        btnGestionMaterias.setOpaque(true);
        btnGestionMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionMateriasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionMateriasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionMateriasMouseExited(evt);
            }
        });
        jPanel1.add(btnGestionMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 250, 50));

        btnGestionAlumnos.setBackground(new java.awt.Color(90, 184, 233));
        btnGestionAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGestionAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnGestionAlumnos.setText("GESTION ALUMNOS");
        btnGestionAlumnos.setOpaque(true);
        btnGestionAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGestionAlumnosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGestionAlumnosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGestionAlumnosMouseExited(evt);
            }
        });
        jPanel1.add(btnGestionAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Logo7060.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnInscripciones.setBackground(new java.awt.Color(90, 184, 233));
        btnInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInscripciones.setForeground(new java.awt.Color(255, 255, 255));
        btnInscripciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInscripciones.setText("INSCRIPCIONES");
        btnInscripciones.setOpaque(true);
        btnInscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInscripcionesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInscripcionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInscripcionesMouseExited(evt);
            }
        });
        jPanel1.add(btnInscripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionAlumnosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAlumnosMouseExited
        // TODO add your handling code here:
        //btnGestionAlumnos.setBackground(Color.decode("#5AB8E9")); // CUANDO SACA EL MOUSE VUELVE AL COLOR QUE ESTABA
        mouseExited(btnGestionAlumnos);
    }//GEN-LAST:event_btnGestionAlumnosMouseExited

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        mouseExited(btnHome);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        Home home = new Home(); 
        home.setSize(WIDTH, HEIGHT); 
        home.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(home);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnGestionAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAlumnosMouseClicked
        // TODO add your handling code here:
        GestionAlumno agregarAlumno = new GestionAlumno();
        agregarAlumno.setSize(WIDTH, HEIGHT);
        agregarAlumno.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(agregarAlumno);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnGestionAlumnosMouseClicked

    private void btnGestionMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionMateriasMouseClicked
        // TODO add your handling code here:
        GestionMateria gestionMateria = new GestionMateria();
        gestionMateria.setSize(WIDTH, HEIGHT);
        gestionMateria.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(gestionMateria);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnGestionMateriasMouseClicked

    private void btnGestionMateriasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionMateriasMouseExited
        // TODO add your handling code here:
        mouseExited(btnGestionMaterias);
    }//GEN-LAST:event_btnGestionMateriasMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        mouseEntered(btnHome);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnGestionMateriasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionMateriasMouseEntered
        // TODO add your handling code here:
        mouseEntered(btnGestionMaterias);
    }//GEN-LAST:event_btnGestionMateriasMouseEntered

    private void btnGestionAlumnosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGestionAlumnosMouseEntered
        // TODO add your handling code here:
        mouseEntered(btnGestionAlumnos);
    }//GEN-LAST:event_btnGestionAlumnosMouseEntered

    private void btnInscripcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscripcionesMouseClicked
        // TODO add your handling code here:
        Inscripciones inscripciones = new Inscripciones();
        inscripciones.setSize(WIDTH, HEIGHT);
        inscripciones.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(inscripciones);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_btnInscripcionesMouseClicked

    private void btnInscripcionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscripcionesMouseEntered
        // TODO add your handling code here:
        mouseEntered(btnInscripciones);
    }//GEN-LAST:event_btnInscripcionesMouseEntered

    private void btnInscripcionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInscripcionesMouseExited
        // TODO add your handling code here:
        mouseExited(btnInscripciones);
    }//GEN-LAST:event_btnInscripcionesMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
        
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGestionAlumnos;
    private javax.swing.JLabel btnGestionMaterias;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnInscripciones;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private void mouseEntered(JLabel btn) {
        btn.setBackground(Color.decode("#0096ce"));
    }

    private void mouseExited(JLabel btn) {
        btn.setBackground(Color.decode("#5AB8E9"));
    }

}

